{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.51b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: 8ff1b9906d5db4b028b599236d11588bb0f791bb23d59fc72bc6cf9b8fbbd4ec

build:
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-api >=1.11,<2.dev0
    - psutil >=5.9.0,<7

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics
  summary: OpenTelemetry Python Instrumentation for System Metrics
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics
  dev_url: https://pypi.org/project/opentelemetry-instrumentation-system-metrics/

extra:
  recipe-maintainers:
    - rxm7706
    - arishamays1
