{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.49b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: 2ef4949c0c0f64e6b7437b8d23e0ee57245ab3d0d38501157bb93f4e4151207c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-api >=1.11,<2.dev0
    - opentelemetry-sdk >=1.25,<2.0
    - psutil >=5.9.0,<7

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics.
  summary: OpenTelemetry System Metrics Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
