{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.47b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: 0c3416cef74dd93fcbcebd51e0fe51e4e7db04151cd5de13e7ab5ae82b19571d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - opentelemetry-instrumentation ==0.47b0
    - python >=3.7
    - opentelemetry-api >=1.11,<2.dev0
    - opentelemetry-sdk >=1.25,<2.0
    - psutil >=5.9.0,<7

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics.
  summary: OpenTelemetry System Metrics Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
